CREATE TABLE STUDENTS(
REGNO VARCHAR2(20),NAME1 VARCHAR2(30),MAJOR VARCHAR2(10),BDATE DATE,
PRIMARY KEY(REGNO));

CREATE TABLE COURSE(
COURSEID NUMBER(10),CNAME VARCHAR2(10),DEPT VARCHAR2(10),
PRIMARY KEY(COURSEID));

CREATE TABLE TEXT(
ISBN NUMBER(10),BOOK_TITLE VARCHAR2(30),PUBLISHER VARCHAR2(30),AUTHOR VARCHAR2(10),
PRIMARY KEY(ISBN));

CREATE TABLE BOOK_ADOPTION(COURSEID NUMBER(9),SEM NUMBER(10),ISBN NUMBER(10),
PRIMARY KEY(COURSEID,ISBN),
FOREIGN KEY(COURSEID) REFERENCES COURSE(COURSEID) ON DELETE CASCADE,
FOREIGN KEY (ISBN) REFERENCES TEXT(ISBN) ON DELETE CASCADE);

CREATE TABLE ENROLL(REGNO VARCHAR2(10), COURSEID NUMBER(10), SEM NUMBER(10), MARKS NUMBER(10),
PRIMARY KEY(REGNO,COURSEID),
FOREIGN KEY(REGNO) REFERENCES STUDENTS(REGNO) ON DELETE CASCADE,
FOREIGN KEY(COURSEID) REFERENCES COURSE(COURSEID) ON DELETE CASCADE);

INSERT INTO STUDENTS VALUES('&REGNO','&NAME','&MAJOR','&DATE');
SELECT * FROM STUDENTS;

INSERT INTO COURSE VALUES(&COURSEID,'&CNAME','&DEPT');
SELECT * FROM COURSE;

INSERT INTO TEXT VALUES(&ISBN,'&BOOK_TITLE','&PUBLISHER','&AUTHOR');
SELECT * FROM TEXT;

INSERT INTO BOOK_ADOPTION VALUES(&COURSEID,&SEM,&ISBN);
SELECT * FROM BOOK_ADOPTION;

INSERT INTO ENROLL VALUES('&REGNO',&COURSEID,&SEM,&MARKS);
SELECT * FROM ENROLL;

INSERT INTO TEXT VALUES(1801,'OS CONCEPTS','WILEY','ABRAHAM');
INSERT INTO BOOK_ADOPTION VALUES(11,3,1801);

SELECT COURSE.COURSEID,COURSE.CNAME,BOOK_ADOPTION.ISBN,TEXT.BOOK_TITLE
FROM COURSE,BOOK_ADOPTION,TEXT
WHERE COURSE.COURSEID=BOOK_ADOPTION.COURSEID AND BOOK_ADOPTION.ISBN=TEXT.ISBN
ORDER BY CNAME ASC;

SELECT COURSE.DEPT
FROM COURSE,TEXT,BOOK_ADOPTION
WHERE TEXT.PUBLISHER='PHI' AND TEXT.ISBN=BOOK_ADOPTION.ISBN AND COURSE.COURSEID=BOOK_ADOPTION.COURSEID;